# Shougo {{{
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
let g:webdevicons_enable_denite = 0
call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'statusline': 0,
            \ 'winheight': 15,
            \ 'updatetime': 100,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'prompt_highlight': 'Function',
            \ 'highlight_matched_char': 'CursorLine',
            \ 'highlight_matched_range': 'CursorLine',
            \ 'highlight_mode_insert': 'StatusLine'
            \ })
'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
# }}}
# Complete {{{
[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
hook_add = '''
let g:deoplete#enable_at_startup = 1
set completeopt+=noinsert
autocmd FileType unite call s:unite_settings()
'''
# }}}
# Airline {{{
[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''
let g:airline_powerline_fonts=1
let g:airline_theme = 'behelit'
let g:airline#extensions#tabline#enabled = 0 " tabs enable
let g:airline#extensions#tabline#fnamemod = ':t' " name without full path
let g:airline#extensions#whitespace#checks = [ 'indent' ] " off whitespaces indicator
let g:airline_left_sep = ''
let g:airline_right_sep = ''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='zenburn'
'''
# }}}
# Syntax {{{

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['jslint']
let g:syntastic_typescript_checkers = ['tsuquyomi', 'tslint']
let g:syntastic_typescript_tsc_args = '--target ES5 --noEmit'

let g:syntastic_html_checkers=['']

let g:synctastic_python_checker = ["flake8"]
let g:syntastic_python_checker_args = "--ignore=E501,W601,W0611"
'''

[[plugins]]
repo = 'chiel92/vim-autoformat'

# [[plugins]]
# repo = 'mattn/emmet-vim'
# on_ft = 'html'

[[plugins]]
repo = 'vimperator/vimperator.vim'
on_ft = 'vimperator'

[[plugins]]
repo = 'python-mode/python-mode'
on_ft = 'python'
hook_add = '''
let g:pymode_python = 'python3'
let g:pymode_options_max_line_length = 120
let g:pymode_options_colorcolumn = 1
let g:pymode_lint_on_fly = 1
let g:pymode_lint_ignore = ['E501', 'E115', 'E116', 'W']
let g:pymode_run_bind = "<C-S-e>"
let g:pymode_virtualenv = 1
let g:pymode_virtualenv_enabled = ''
let g:pymode_virtualenv_path = ''
let g:pymode_doc = 0
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = 'css, sass'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

# [[plugins]]
# repo = 'othree/html5.vim'
# on_ft = 'html'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'TypeScrypt'
hook_add = '''
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]]
repo = 'Valloric/MatchTagAlways'

# }}}
# NerdTree {{{
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeShowHidden=1
let g:NERDTreeMinimalUI=1
let g:NERDTreeDirArrows=0
let g:NERDTreeQuitOnOpen=1
let g:NERDTreeAutoDeleteBuffer=1
let g:NERDTreeDirArrowExpandable = '◌'
let g:NERDTreeDirArrowCollapsible = '●'
let g:NERDTreeIgnore = ['\.pyc$', '.DS_Store', '__pycache__']
'''

[[plugins]]
repo = 'dsimidzija/vim-nerdtree-ignore'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
let g:NERDTreeFileExtensionHighlightFullName=1
let g:NERDTreeExactMatchHighlightFullName = 1
let g:NERDTreePatternMatchHighlightFullName = 1
let g:NERDTreeHighlightFoldersFullName = 1 " highlights the folder name
'''

# }}} 
# Devicons{{{
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
autocmd FileType nerdtree setlocal nolist
'''
# }}}
# Git {{{

#[[plugins]]
#repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'chemzqm/vim-easygit'
hook_add = '''
let g:easygit_enable_command = 1
'''

[[plugins]]
repo = 'chemzqm/denite-git'

# }}}
# Comments {{{
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
'''
# }}}
# Templates {{{
[[plugins]]
repo = 'tibabit/vim-templates'
hook_add = '''
let g:tmpl_search_paths = ['~/.config/nvim/templates/']
'''
# }}}
# ctags {{{
[[plugins]]
repo = 'craigemery/vim-autotag'
# }}}
# ENV {{{
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
hook_add = '''
let g:virtualenv_auto_activate = 1
'''
on_ft = 'python'
# }}}
# Sessions {{{
[[plugins]]
repo = 'tpope/vim-obsession'
# }}}
